# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "nabedeapp"
client_id = "5edceca177d651008a6319dce9175fb1"
application_url = "https://sale-strange-mid-introduction.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sale-strange-mid-introduction.trycloudflare.com/auth/callback",
  "https://sale-strange-mid-introduction.trycloudflare.com/auth/shopify/callback",
  "https://sale-strange-mid-introduction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nabedeecom.myshopify.com"
